export type EnvironmentVariables =
  | "NODE_ENV"
  | "AWS_ACCESS_KEY"
  | "AWS_SECRET_KEY"
  | "DIGITALOCEAN_SPACES_SECRET_ACCESS_KEY"
  | "DIGITALOCEAN_SPACES_ACCESS_KEY_ID"
  | "AWS_REGION"
  | "GOOGLE_API_KEY"
  | "DISCORD_WIKISUBMISSION_TOKEN"
  | "DISCORD_WIKISUBMISSION_CLIENT_ID"
  | "DISCORD_SUBMISSIONMOD_TOKEN"
  | "DISCORD_SUBMISSIONMOD_CLIENT_ID"
  | "DISCORD_TESTING_TOKEN"
  | "DISCORD_TESTING_CLIENT_ID";
