export type EnvironmentVariables =
  | "NODE_ENV"
  | "AWS_ACCESS_KEY"
  | "AWS_SECRET_KEY"
  | "DIGITALOCEAN_SPACES_SECRET_ACCESS_KEY"
  | "DIGITALOCEAN_SPACES_ACCESS_KEY_ID"
  | "AWS_REGION"
  | "GOOGLE_API_KEY"
  | "DISCORD_TOKEN"
  | "DISCORD_CLIENT_ID"
  | "DISCORD_TOKEN_DEV"
  | "DISCORD_CLIENT_ID_DEV";
